### PR TITLE
FAQ Page updated

### PR DESCRIPTION
**Pull request by aishanibhalla**
Review it according to the master and merge it,

thanks !

### CODE REVIEW

**Comment by atrookey** [comment]
Hey Aishani,

Why did you submit /about/index.html instead of /faq/index.html or /resources/index.html?

-Alex

**Comment by atrookey** [comment]
Hey,

The resources page looks good but the faq page still doesn't scale very well on mobile.  Try moving <div class="col-md-12"> so that its directly beneath <div class="row">.  Right now you have <div class="box"> between them and I think its screwing things up

-edited

-Alex

**Comment by aishanibhalla** [comment]
I am pretty sure now it should be fixed :)

**Comment by atrookey** [comment]
Aishani,  a couple of the div tags in faq/index.html weren't lined up properly but I took care of fixing them.  Everything else looks great!  I'll merge your code with master

**Pull request merged**
