### PR TITLE
changed the front page extensively.

### PR DESCRIPTION
**Pull request by brijeshrakholia**
@atrookey : I have changed the front page as per our discussion today. Please have a look and let me know if it looks nice. :) 
Thanks!

### CODE REVIEW

**Comment by atrookey** [comment]
Hey Brijesh,

I like the changes you made!  The front page looks much better with a background image.  However, I think the current image looks too spooky.  I'd like to replace it with a different image before I merge your pull request

Alex

**Comment by brijeshrakholia** [comment]
Hi Alex,

Yeah, even I thought that its looking a bit spooky. Let me search for other images and see if it looks nicer. I will get back asap. 

Thanks,
Brijesh

**Comment by brijeshrakholia** [comment]
I have changed the picture. Have a look and let me know..

**Comment by atrookey** [comment]
Hey Brijesh,

Nice work!  I'm going to approve your request.  Still not too keen on the background image though.  I think we should try and get away from photos of Davis

-Alex

**Pull request merged**
